CREATE DATABASE techfit;
USE techfit;

CREATE TABLE usuarios (
    id INT AUTO_INCREMENT PRIMARY KEY,
    nome VARCHAR(100) NOT NULL,
    email VARCHAR(120) NOT NULL UNIQUE,
    senha VARCHAR(255) NOT NULL,
    criado_em DATETIME DEFAULT CURRENT_TIMESTAMP
);
ALTER TABLE usuarios
ADD COLUMN nivel_acesso VARCHAR(50) NOT NULL DEFAULT 'comum';
ALTER TABLE usuarios ADD COLUMN telefone VARCHAR(20) AFTER email;